### ISSUE TITLE
Fatality.win

### ISSUE THREAD

**Issue by ScReAmLoL** [avangersKinkyClient/KinkyClient-CSGO-Cheaters-Pack-dll-files#3]
When i inject fatality.win, cs starts to freeze and then speed up. Then it immediately closes, but the first time when i injected it it worked. I used multiple injectors and i have also other cheats like onetap v3 and getrekt.xyz.

**Comment by RXVAN** [comment]
its OUTDATED idiot

**Comment by avangersKinkyClient** [comment]
Thank you for the message i update the hole list tonight with update time information and even adding a lot of new cheats i got
